### PR TITLE
Add config for custom sendmail config (for Toolforge)

### PR DESCRIPTION
**Pull request by samwilson**
This is just an idea I've got about making it email us critical errors.

### CODE REVIEW

**Comment by samwilson** [comment]
hm, seems there's more to it in the php container:

>  Process could not be started [sh: 1: /usr/sbin/exim: not found]

**Comment by MusikAnimal** [comment]
Fantastic idea!! I don't know how the mailer things work, but we should do this, if it's not incredibly difficult.

**Comment by samwilson** [comment]
Yeah, I've got it working locally. The trouble on toolforge is that there's no MTA in the PHP container, and I don't know if we've got a SMTP server we can use (actually, maybe we do?).

**Comment by MusikAnimal** [comment]
I would ask in #wikimedia-cloud on IRC. Bryan certainly would know.

**Pull request merged**
