### PR TITLE
Switch from Assetic to Webpack Encore

### PR DESCRIPTION
**Pull request by samwilson**
In preparation for upgrading to Symfony 4, remove Assetic and
install Webpack Encore. This entails a few changes:

* give global functions an application scope;
* introduce npm
* deployment process changes

Bug: https://phabricator.wikimedia.org/T202471

### CODE REVIEW

**Comment by samwilson** [comment]
@mooeypoo do you have an opinion on how the JS functions etc here are organised and named?

**Comment by MusikAnimal** [comment]
@aezell Looks like we got that covered at https://github.com/wikimedia/grantmetrics/pull/101/files#diff-354f30a63fb0907d4ad57269548329e3R33 and the Travis build is passing. No Jenkins for this project, though Travis sounds like he could be a butler, too. Maybe they're related.

**Comment by aezell** [comment]
@MusikAnimal Cool. Good to know that "it just works."

**Comment by aezell** [comment]
This looks so much cleaner and easier to work with now.

**Pull request merged**
